### ISSUE TITLE
Additional data issues

### ISSUE THREAD

**Issue by ryanmberry** [doehm/survivoR#14]
Here's a small list of additional data issues I've found.

1. US07 vote_history - Any pre-merge vote by an eventual outcast has their tribe listed as "The Outcasts" instead of their original tribe.
2. US07 - The outcast return vote is not represented in the data. Weird-as-heck edge case, though.
3. According to https://en.wikipedia.org/wiki/Survivor:_Pearl_Islands episode descriptions, Osten's quit was handled as a verbal unanimous vote. The data set doesn't record this vote, nor is it tracked in the voting chart on the wiki page. This is different from how other verbal votes have been handled on both wikipedia and in the data (S26 Brandon, S34 Jeff). A case could be made for populating US07 order 8 with this vote data.
4. US07 order 9 - both returning outcasts (Burton and Lillian) were granted immunity in this vote. Burton also won the immunity challenge, and he awarded it to Rupert. This is not reflected in the data.
5. US16 order 16 - Erik won individual immunity, but he gave it to Natalie. This is not reflected in the data. (Are there other instances of immunity necklaces being transferred? I don't recall and haven't researched.)
6. US26 order 11 - Votes against Malcolm are not marked as nullified in the data.
7. US37 order 10 - Nick voted twice for Dan, but only one vote exists in the data.
8. filter(castaways, version == "US", season == 43). Owen (the second runner-up, order 16) is the last row of this data instead of the 16th. This is different from how these rows are sorted for other seasons.

**Comment by doehm** [comment]
Hi,

Issues are now resolved and on Git. I'll make a release to CRAN in a week or two

In summary:

1. Done. Weird though. Must have been a bad join
2. I'm keen to leave that out of the vote history for the moment.
3. Good pick-up. It's more similar to Jeff's vote out in US34 where he didn't actually vote so it is recorded as none. I've done the same for Osten
4. Done
5. It's reflected in the data such that it is recorded as a win for Erik in challenge_results. vote_history should be interpreted as who attended at least part of tribal council and who was immune to the vote. It's recorded correctly here for how it should be used.
6. Done. Good pick-up.
7. Done. Good pick-up
8. No data errors but have sorted the data for consistency.

If all good I'll make this issue of as closed

Dan

**Comment by ryanmberry** [comment]
I think your fixes for these blew away all of the fixes from my other post: https://github.com/doehm/survivoR/issues/7#issuecomment-1362229781

One follow-up on #7 (Nick's second vote for Dan). This vote needs to be given the vote_event "Steal a vote" to be consistent with past other stolen votes.

Additionally, at this same Tribal Council, the data gives Alison's NA vote the vote_event "Steal a vote", even though her vote was stolen from her. For consistency, the "Steal a vote" vote_event should only be used on the vote cast by the player who stole it, not the player who was stolen from.

This leads me to think - wouldn't it be great if all NA votes had a reason why they're NA in the vote_event field? Examples that aren't yet represented include "Final 3 Non-voting", "Removed From Revote", "Vote Stolen", "Quit Vote" (which represents the US07 Osten and US34 Jeff cases), "Vote Blocked" (US34 order 11 Tai, US39, order 6 Jason), "Lost at Ghost Island", "Lost at Island of the Idols", "Safety Without Power", "Lost (Beware Advantage)", "Lost at Shipwheel Island". Vote losses resulting from contestant journeys may be a combinable group.

If good wording for these can be agreed upon, I wouldn't mind trying to take on the task of adding that NA vote_event data. (I'd need to learn how exactly to contribute here, but I'd be happy to take it on.)

Also, the "White Rock" vote_event seems to be named "Whte Rock." Would it be worthwhile to change rock draw vote_events to "Good Rock"/"Bad Rock" to be consistent across seasons? (For context, the rock events in US04 are Purple and Yellow.)

**Comment by ryanmberry** [comment]
A "Final 3 Non-Voting" vote_event could also be named "Only One Option", which would also encompass the strange case of Denise and Sarah's US40 order 17.2 NA votes at Final Six.

**Comment by doehm** [comment]
hmm, it shouldn't have. It is possible I didn't make a final push though. I've recommitted the changes. Could you please install from git and see if the changes have come through?

Cleaning up vote_event has been on the to-do list. There are a few inconsistencies in terms of phrasing, spelling and case. Definitely needs to be cleaned up. I think having a value for each NA vote is a good idea. I'll set up a doc so we can create a mapping. vote_event has turned into a secondary descriptive field but should maintain consistency where possible.

I like the idea of 'good rock' 'bad rock'. I'm inclined to use 'Rock draw (safe)' and 'Rock draw (eliminated)' as the values since 'Rock draw' is the actual event taking place and in brackets is the result.

**Comment by ryanmberry** [comment]
I just checked again and all fixes that you committed from both of my lists are now in and working as expected (as well as the US37 vote steal issue I mentioned in a different post).

I have some outstanding thoughts about immunity necklace giveaways that I'll put in another post for organization's sake. This thread can probably be closed now.
