### ISSUE TITLE
Errors in Survivor45 E8 Data -- vote_history *Potential spoilers below*

### ISSUE THREAD

**Issue by jresser04** [doehm/survivoR#17]
Totally understand that the Survivor 45 episode 8 data are fresh, but found these errors in the vote_history data pulled from GitHub so figured I would flag them:

1) Bruce is incorrectly listed as voting for Jake in `vote`.

2) Jake is incorrectly listed in `voted_out` and `voted_out_id`.

**Comment by doehm** [comment]
Thanks heaps and good catch! I'll push an update to git in a couple of hours. I'll let you know when it's up.

**Comment by doehm** [comment]
I've made the correction and pushed to git. 

Let me know if you find anything else 👍
