### ISSUE TITLE
Castaways - original_tribe incorrect (season 44)

### ISSUE THREAD

**Issue by hi1l** [doehm/survivoR#18]
Original tribe data in the castaways database for season 44 has errors. 

US0646 - Jaime - Soka (should be Ratu)
US0648 - Lauren - Soka (should be Ratu)
US0655 - Josh - Ratu (should be Soka)
US0656 - Josh - Ratu (should be Soka)

**Comment by doehm** [comment]
Hi, thanks for the heads ups on the data errors. This has been corrected.

Just confirming that the last one should be Matt::
US0656 - Matt - Ratu (should be Soka)

If you install from git it's good to go.
