### ISSUE TITLE
Missing immunity winners

### ISSUE THREAD

**Issue by JedGrabman** [doehm/survivoR#21]
I've found some instances where no individual immunity winner is listed for a post-merge tribal. There's probably some edge cases, but glancing through, it looks like there are legitimate data issues involved. 

    library("survivoR")
    library(dplyr)

    nobody_immune = vote_history %>%
      filter(tribe_status == "Merged") %>%
      filter(vote_order == 1) %>%
      select(version, season, episode, day, immunity) %>%
      group_by(version, season, episode, day) %>%
      summarise(immunity_winner = any(immunity == "Individual")) %>%
      filter(is.na(immunity_winner))

    nobody_immune %>%
      print(n=nrow(nobody_immune))

version|season|episode|day|immunity_winner
|--|--|--|--|--|
AU|3|24|49|NA 
AU|5|14|30|NA 
AU|5|15|32|NA 
AU|5|18|38|NA 
AU|5|19|40|NA 
AU|5|20|42|NA 
AU|5|21|44|NA 
AU|5|22|46|NA 
AU|5|23|47|NA 
AU|5|24|49|NA 
AU|7|20|40|NA 
SA|6|16|38|NA 
SA|7|9|22|NA 
SA|7|18|38|NA 
SA|8|13|33|NA 
SA|8|14|35|NA 
SA|8|15|37|NA 
SA|8|16|38|NA 
SA|9|14|23|NA 
UK|3|16|33|NA 
US|1|13|37|NA 
US|2|7|21|NA 
US|3|12|33|NA 
US|4|14|37|NA 
US|7|7|19|NA 
US|7|9|24|NA 
US|7|14|37|NA 
US|10|14|37|NA 
US|12|14|36|NA 
US|13|15|38|NA 
US|14|9|24|NA 
US|14|10|27|NA 
US|14|14|37|NA 
US|15|9|27|NA 
US|15|12|33|NA 
US|16|14|38|NA 
US|17|13|38|NA 
US|18|14|38|NA 
US|19|10|27|NA 
US|19|15|38|NA 
US|23|8|21|NA 
US|25|11|30|NA 
US|26|11|30|NA 
US|27|12|32|NA 
US|28|13|38|NA 
US|29|13|35|NA 
US|30|14|38|NA 
US|31|14|36|NA 
US|32|14|37|NA 
US|35|8|21|NA 
US|35|13|37|NA 
US|36|12|35|NA 
US|37|13|38|NA 
US|39|10|30|NA 
US|40|14|36|NA 
US|41|12|23|NA 
US|41|13|24|NA 
US|42|7|14|NA 
US|42|8|16|NA 

Additionally, I know there's at least one edge case this missed. Marcus won individual immunity in season 17, episode 6, day 21. That was a pre-merge individual challenge, so it doesn't show up on this list.

I did attempt to pull the immunity winners from the challenge results, but there's no direct way to match up a challenge with the corresponding tribal council. I attempted joining on the episode, but some episodes have multiple immunity challenges (mostly finales) and it wouldn't surprise me if there was a tribal on a different episode than a challenge, so the data isn't perfect.

    winners_ii = challenge_results %>% 
      filter(result == "Won" | result == "Won (immunity only)") %>%
      filter(challenge_type == "Immunity" | challenge_type == "Immunity and Reward") %>%
      filter(tribe_status == "Merged")
    
    possible_ii_winners = nobody_immune %>%
      left_join(winners_ii, by = c("version", "season", "episode")) %>%
      select(version, season, episode, castaway)
    
    possible_ii_winners %>%
      print(nrow(possible_ii_winners))

**Comment by doehm** [comment]
Hey, I've had a look at this and starting to go through it. There are some edge cases such that that was no one with immunity but also some data issues. Pretty sure I know what's happened there. I should be able to complete it by the end of the day.

Just a heads up, to join the `vote_history` and `challenge_results` tables use `version_season`, `episode`, and `order`/`n_boots`. A poor choice I made early in development was call the boot order `order` so it's not obvious how it relates to `n_boots`. Essentially, `order` on the vote history table is the n'th boot.

As an example, here's some code to join challenge name onto vote history. note there are some multiple immunity challenges so it will give a many-to-many match. (also just going through and double checking all of this).

```
df_challenge_names <- survivoR::challenge_results |> 
  # get challenge name
  left_join(
    survivoR::challenge_description |> 
      distinct(version_season, episode, challenge_id, challenge_name = recurring_name),
    by = c("version_season", "episode", "challenge_id")
  ) |> 
  filter(challenge_type %in% c("Immunity", "Immunity and Reward")) |> 
  distinct(version_season, episode, n_boots, challenge_name)

survivoR::vote_history |> 
  # minus one from order to create the boot key
  mutate(n_boots = order - 1) |> 
  # join on challenge name
  left_join(
    df_challenge_names, 
    by = c("version_season", "episode", "n_boots")
  )
```

I'll let you know when it's available on Git

**Comment by doehm** [comment]
I've made the corrections to `vote_history` immunity field and now available on Git. The code below, adapted from yours above should return 5 rows which are edge cases but correct. This has been pulled into a test required to pass before release.

```
nobody_immune <- survivoR::vote_history |>
    filter(tribe_status == "Merged") |>
    filter(vote_order == 1) |>
    group_by(version_season, episode, order) |>
    summarise(immunity_winner = sum(immunity == "Individual", na.rm = TRUE)) |>
    filter(immunity_winner == 0)
```

I'll be taking a look to make sure there is consistency between the `challenge_results` winners and `vote_history` immunity holders. It should be but may be a few edge cases again.

**Comment by JedGrabman** [comment]
Great, thanks for the quick fix and the tip! Feel free to either close or leave open if you want to also use this issue for the `challenge_results` immunity work

**Comment by doehm** [comment]
No worries! I'll close it for now, but please open a new one if you find another issue. I usually get to them pretty quickly.
