### ISSUE TITLE
Capitalization inconsistencies in advantage types

### ISSUE THREAD

**Issue by JedGrabman** [doehm/survivoR#24]
In `advantage_details`, there are several pairs of values for `advantage_type` that vary only by capitalization (e.g. `Hidden immunity idol` vs. `Hidden Immunity Idol`)

The following code snippet shows the affected types
```
library(dplyr)
advantage_types = advantage_details$advantage_type %>% unique() %>% sort()
advantage_types[advantage_types %>% tolower() %>% duplicated()]
```
Results:
```
"Challenge Advantage"  "Extra Vote" "Hidden Immunity Idol" "Idol Nullifier" "Knowledge is Power" "Safety Without Power" "Steal a Vote" 
```

**Comment by doehm** [comment]
The capitalization is now fixed. For consistency, I've added `snakecase::to_title_case` to a step in the pipeline. I've also added a test so should be consistent going forward.

Install from Git for the updates.

Thanks for picking this up!

**Comment by JedGrabman** [comment]
Thanks! I also had the thought that it might be wise to test against an explicit list of acceptable values. That would protect against any possible typos in the future.
