### ISSUE TITLE
Advantage related data issues

### ISSUE THREAD

**Issue by JedGrabman** [doehm/survivoR#25]
I've found a few data issues while playing around with `advantage_movement` and `advantage_details`. Here they are with code to reproduce them (which might be helpful with some modifications for use in tests)

1.) advantages with no `advantage_id`

```
library(dplyr)
advantage_details %>% 
  filter(is.na(advantage_id)) 
```

2.) Advantages in `advantage_movement` without a corresponding entry in `advantage_details`:

```
advantage_movement %>%
  anti_join(advantage_details, join_by(version, season, advantage_id)) %>%
  select(version, season, advantage_id) %>%
  distinct()
```

3.) Multiple entries with identical identifiers in advantage_details

```
advantage_details %>%
  filter(!is.na(advantage_id)) %>%
  select(version, season, advantage_id) %>%
  group_by(version, season, advantage_id) %>%
  count() %>%
  filter(n > 1)
```

4.) `advantage_id` skips numbers (assuming ids are meant to be sequential within each season)

```
advantage_details %>%
  select(version, season, advantage_id) %>%
  group_by(version, season) %>%
  mutate(max_advantage_id = max(advantage_id)) %>%
  group_by(version, season, max_advantage_id) %>%
  count() %>%
  filter(max_advantage_id != n)
```

**Comment by doehm** [comment]
All of these should be fixed now but will be double-checking the tables.

1. No advantages without an ID. Really not sure how this one slipped through
2. advantage_movement and advantage_details are now synced
3. No more dupes
4. Some of these ok (US40) although I might changed it to be sequential

I made a couple of other minor tweaks as well.

Thanks again! That first one identified an issue with the pipeline that I hadn't found yet so thanks for letting me know.
