### ISSUE TITLE
Season 46 vote error: Tevin vs. Hunter

### ISSUE THREAD

**Issue by stiles** [doehm/survivoR#26]
The `vote_history.rda` has Hunter being voted off twice: In episodes 8 and 9. Tevin was voted off in episode 8. 

<img width="1368" alt="survivoR_vote_history" src="https://github.com/doehm/survivoR/assets/232237/26693c3c-74ed-4dd7-9cd1-54ae01f678aa">

Tevin's ID is US0694
Hunter's ID is US0684

**Comment by doehm** [comment]
This checks out on my end 

```
survivoR::vote_history |> 
  filter(season == 46) |> 
  distinct(episode, voted_out)
```
![image](https://github.com/doehm/survivoR/assets/45231756/30fd552e-6b9a-4600-8830-58efdf631c6b)

Would you be able to install from Git and check if that issue is resolved?

`devtools::install_github("doehm/survivoR")`

**Comment by stiles** [comment]
I checked the source files and it's correct. Appreciate your help.
