### ISSUE TITLE
Update the Cook Islands country value in season summary

### ISSUE THREAD

**Issue by stiles** [doehm/survivoR#27]
The row for _Survivor: Cook Islands_ in the `season_summary` table lists "Islands" as the value in the `country` column — not "Cook Islands" or "New Zealand". 

The Cook Islands is a weird one. It's part of the Realm of New Zealand but basically autonomous. Its residents are considering a referendum to join the United Nations as a member state, and it has diplomatic relations with ~50 countries, but it's unclear which value to use in the `country` column. But either would be better than "Islands," I guess. 

Hope you don't mind these occasional correction requests. And I'm sorry I'm not better with R or I would submitted a proper pull request. I should pick it up again. Here's the offending line in that table: 

<img width="705" alt="stiles_screenshot 2024-06-26 at 4 31 07 PM" src="https://github.com/doehm/survivoR/assets/232237/7a17dde9-1f1b-480f-93b1-a4694767b067">

**Comment by stiles** [comment]
Thanks again for the work y'all do here. I love this repo!

**Comment by stiles** [comment]
While we're here, this one should probably be more specific and list "French Polynesia" right? Polynesia is a region that's hosted other seasons, such as Cook Islands and Samoa. 

<img width="784" alt="stiles_screenshot 2024-06-26 at 5 16 08 PM" src="https://github.com/doehm/survivoR/assets/232237/8d2a4f7c-22ea-4bb2-a2d9-5eb874a8812e">

**Comment by doehm** [comment]
Thanks for picking this one up. I've updated it to Cook Islands and French Polynesia. Must have been a regex issue.

Technically I think the country should be France rather than French Polynesia. I'm going to think about it more about what makes the most sense. But for now it's French Polynesia.

It's ready to go on Git!
