### ISSUE TITLE
Survivor 47 Episode 8 initial votes

### ISSUE THREAD

**Issue by JedGrabman** [doehm/survivoR#28]
Currently, the initial votes for S47E8 have Caroline, Sol, Sue and Teeny voting for Sam, and Andy, Gabe, Genevieve & Kyle voting for Sierra. 

While, the initial votes during the Sam/Sierra split vote were not shown during the episode, it seems that the [consensus based on handwriting](https://www.truedorktimes.com/s47/boxscores/e8.htm) is that all the Tukus voted for Sierra, while the rest voted for Sam. The Wikipedia article and Fandom wiki both have been updated at some point to have this breakdown as well.

This would have Sue & Caroline voting for Sierra, and Andy & Genevieve voting for Sam.

**Comment by doehm** [comment]
Thanks for the heads up. That's been corrected and pushed to Git.
