### ISSUE TITLE
Request: Data on recurring challenges

### ISSUE THREAD

**Issue by lakikowolfe** [doehm/survivoR#4]
Love this package! Thank you so much for the time and effort you put into this. I feel real needy making a data request because seriously this is great.

I was wondering if there was any interest in collecting information on recurring challenges. I think it'd be cool because it would enable some analysis of common themes amongst winners. I'm pretty sure all the info you'd need is in the [wiki](https://survivor.fandom.com/wiki/Category:Recurring_Challenges).

I would also be interested in helping you collect this data 🤷 just throwing that out there.

**Comment by doehm** [comment]
Hey, thanks so much! Took a while pulling together so it's great to hear that you like it!

Definitely. I want to keep adding as much data as I can to it and I think more detail on recurring challenges would be a cool feature. 

I'm keen for you to contribute, and encourage it! If you were happy to pull the challenge data I'll work it into the package and list you as a contributor.

In also looking for more details on hidden immunity idols ie when found, when played and on who, who knew about them. At the moment I just have who had their vote nullified by a hidden immunity idol.

Let me know if you want to contribute.

**Comment by lakikowolfe** [comment]
Great! I've been working on some code to scrape the Survivor Fandom wiki. It's slow going, but I'll let you know when I have something for you.

**Comment by doehm** [comment]
Thanks! 

The challenge data looks pretty good. A data frame with the following fields would be great: season_name, season, episode_name, episode, day, challenge_type, challenge_name, winners, description, rules. 'day' might be difficult but could use the tribal council day that I've used on the reward and immunity tables. I'm also thinking about consolidating the rewards and immunity tables into a single challenges table which this could add to.

I'll look into parsing the hidden immunity idol table and building that in. Thanks for the link!

Feel free to email me (danieloehm@gmail.com) if you want to share anything or chat more about the details.

**Comment by lakikowolfe** [comment]
Awesome, I was thinking the same thing re: fields to pull into the dataset. 

Some notes:

- This list also includes when the challenge occurs in redemption island duels. I'll keep all that information just in case you want to include info about redemption island/duels down the line
- Some of the challenges list winners as the tribe that won rather than the individual winner names. Right now it doesn't seem like there is a good way to map castaways to tribes they were a part of. Does it make sense to also build out the castaway dataset to include tribes? I'll probably have to do this to map castaways to challenge winners and can share that back with you as well!

**Comment by doehm** [comment]
Re: email, I don't mind but giving the option if there are things easier shared there.

I think the redemption island challenges and duels are good to have. In the structure of the table, challenge_type could have reward, immunity, duel, and anything similar. Could also include fire challenges, which are already available on the vote_history table but might be good for completeness. I'll be able to add that in fairly easily.

Tribe exists on the castaway table, the only issue is knowing if it is after the tribe swap. Could be worth separating this out to make it easier.

**Comment by doehm** [comment]
I've added 2 new datasets under development that might help with adding challenges. I've combined the rewards and immunity tables to create a new nested data frame 'challenges'. Each row is a challenge and flagged as either reward or immunity. It includes the castaways and tribe that won the challenge. Should be easier to add duels and other challenges, as well as the challenge name. 

The other dataset is 'tribe_mapping'. Mostly used to create the challenges data set. Let me know if this helps at all!

**Comment by lakikowolfe** [comment]
awesome! That will be helpful. I've had to pause on this for a minute to tend to other work/life things but I'm excited to get back to it this week.

**Comment by doehm** [comment]
Just an update on this one to close the issue. There have been some major updates to the challenges data. Now includes all recurring challenges, challenge names, duels, whether they were the winner or chosen to participate in the reward. The challenge descriptions have been recorded as binary features. Please see the notes for details. 

If you're still using the data you might find this interesting / useful.
