### ISSUE TITLE
challenges dataframe not working?

### ISSUE THREAD

**Issue by wbk39** [doehm/survivoR#5]
Great package! Thank you for putting this together. However, it doesn't seem like the challenges data is loading correctly? Whenever I try to look at it, it tells me that it can't be found. Thanks!

**Comment by doehm** [comment]
Hey, thanks! Could try installing the package again? The challenges data set was introduced in v0.9.3.

**Comment by wbk39** [comment]
Hello,

Thank you so much. That seems to have fixed it!

Best,
Whitney
